version: 2
updates:
  # NuGet dependencies
  - package-ecosystem: "nuget"
    directory: "/dfa/src/API"
    target-branch: "feature/dfa_cleanup"
    schedule:
      interval: "daily"
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/dfa/src/UI"
    target-branch: "feature/dfa_cleanup"
    schedule:
      interval: "daily"
