name: ci-dfa-portal-ui

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "dfa/src/UI/**"
      - ".github/workflows/ci-dfa-portal-ui.yml"

env:
  IMAGE_NAME: dfa-portal-ui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Build image
        working-directory: ./dfa/src/UI
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
