name: ci-dfa-portal-api

on:
  push:
    branches: [feature/dfa_cleanup]
  #pull_request:
  #  types: [opened, reopened, edited, synchronize]
    paths:
      - "dfa/src/API/**"
      - ".github/workflows/ci-dfa-portal-api.yml"

env:
  IMAGE_NAME: dfa-portal-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Build image
        working-directory: ./dfa/src/API
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --build-arg GITHUB_NUGET_USERNAME=github --build-arg GITHUB_NUGET_PAT=${{ secrets.GITHUB_TOKEN }}
